line-length = 100
indent-width = 4

[lint]
select = [
  "A",
  "AIR",
  "ANN",
  "ARG",
  "ASYNC",
  "B",
  "BLE",
  "C4",
  "C90",
  "CPY",
  "DOC",
  "DJ",
  "DTZ",
  "E",
  "EM",
  "EXE",
  "F",
  "FAST",
  "FBT",
  "FIX",
  "FLY",
  "FURB",
  "G",
  "I",
  "ICN",
  "INT",
  "INP",
  "ISC",
  "LOG",
  "N",
  "NPY",
  "PD",
  "PERF",
  "PGH",
  "PIE",
  "PL",
  "PT",
  "PTH",
  "PYI",
  "Q",
  "RET",
  "RSE",
  "S",
  "SIM",
  "SLF",
  "SLOT",
  "T10",
  "T20",
  "TC",
  "TD",
  "TID",
  "TRY",
  "UP",
  "RUF",
  "W",
  "YTT",
]

ignore = ["E501", "ANN401", "ISC001", "W191"]


dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.per-file-ignores]
"src/**/*.py" = ["T20"]
"test/**/*.py" = ["S101", "ANN201", "ANN202"]
"__init__.py" = ["F401"]

[lint.pycodestyle]
max-doc-length = 72

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = 72
